# Generated by Django 5.0.1 on 2024-02-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('imagePath', models.CharField(max_length=255)),
                ('success', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('cls', models.IntegerField()),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('requestTimestamp', models.IntegerField()),
                ('responseTimestamp', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='AiAnalysisLog',
        ),
    ]
