# Generated by Django 5.0.1 on 2024-02-04 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_yourmodel_delete_aianalysislog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YourModel',
            new_name='ai_analysis_log',
        ),
    ]
