# Generated by Django 5.0.1 on 2024-02-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_yourmodel_ai_analysis_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai_analysis_log',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
