# Generated by Django 5.0.1 on 2024-02-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_ai_analysis_log_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai_analysis_log',
            name='cls',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ai_analysis_log',
            name='confidence',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ai_analysis_log',
            name='imagePath',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ai_analysis_log',
            name='message',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ai_analysis_log',
            name='requestTimestamp',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ai_analysis_log',
            name='responseTimestamp',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ai_analysis_log',
            name='success',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
